/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gss.fca.gui.impl;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import br.com.gss.fca.Messages;
import br.com.gss.fca.gui.AbstractPanel;
import br.com.gss.fca.gui.MainWindow;

/**
 * Panel with the "I agree" text.
 * @author Paula.Fernandes
 */
public class InitPanel extends AbstractPanel{

	private static final long serialVersionUID = 1L;
	private boolean allowNext = false;
	
    /**
     * Creates new form InitPanel
     */
    public InitPanel(MainWindow mainWindow) {
    	super(mainWindow);
        initComponents();
        initActions();
    }

    private void initActions() {
    	if(this.btnAgree!=null){
    		this.btnAgree.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					setAllowNext(true);
					refreshFeedback();
				}

			});
    	}
    	if(this.btnDontAgree!=null){
    		this.btnDontAgree.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					setAllowNext(false);
					refreshFeedback();
				}
			});
    	}
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        txtTitle = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        btnAgree = new javax.swing.JRadioButton();
        btnDontAgree = new javax.swing.JRadioButton();
        scrollPanel = new javax.swing.JScrollPane();
        txtTerm = new javax.swing.JTextPane();
        
        

        setPreferredSize(new java.awt.Dimension(500, 300));

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTitle.setText(Messages.getString("window.init.title"));

        txtDescription.setText(Messages.getString("window.init.description"));
        txtTerm.setText(Messages.getString("window.init.term"));

        btnAgree.setText(Messages.getString("btn.accept"));
        btnDontAgree.setText(Messages.getString("btn.dont.accept"));

        txtTerm.setEditable(false);
        scrollPanel.setViewportView(txtTerm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDontAgree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgree))
                    .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgree)
                    .addComponent(btnDontAgree))
                .addContainerGap())
        );
        scrollPanel.getVerticalScrollBar().setValue(10);
        txtTerm.setCaretPosition(0);
        
        groupRadioAgree = new javax.swing.ButtonGroup();
        groupRadioAgree.add(btnAgree);
        groupRadioAgree.add(btnDontAgree);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAgree;
    private javax.swing.JRadioButton btnDontAgree;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JTextPane txtTerm;
    private javax.swing.JLabel txtTitle;
    private javax.swing.ButtonGroup groupRadioAgree;
    // End of variables declaration//GEN-END:variables
    
    
	private void setAllowNext(boolean allowNext) {
		this.allowNext = allowNext;
	}

	@Override
	public boolean allowNext() {
		return allowNext;
	}
	
	@Override
	public boolean allowPrevious() {
		return false;
	}

	@Override
	public void onNext() {
		//do nothing
	}

	@Override
	public void onPrevious() {
		//do nothing		
	}

	public void onError(String error, Exception e) {
		
	}

	public void onFeedback(String message) {
		
	}

	
}
